// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A Genkit flow that recommends the most efficient power flow algorithm based on the grid configuration.
 *
 * - `recommendAlgorithm` - A function that takes grid properties as input and returns an algorithm recommendation with reasoning.
 * - `AlgorithmRecommendationInput` - The input type for the `recommendAlgorithm` function.
 * - `AlgorithmRecommendationOutput` - The return type for the `recommendAlgorithm` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AlgorithmRecommendationInputSchema = z.object({
  busCount: z.number().describe('The number of buses (nodes) in the power grid.'),
  lineImpedancePattern: z
    .string()
    .describe(
      'A description of the line impedance patterns in the grid (e.g., uniform, highly variable).'
    ),
  nodeCount: z.number().describe('The number of nodes in the power grid.'),
});
export type AlgorithmRecommendationInput = z.infer<typeof AlgorithmRecommendationInputSchema>;

const AlgorithmRecommendationOutputSchema = z.object({
  algorithm: z
    .enum(['Newton-Raphson', 'Gauss-Seidel', 'DC Power Flow', 'Fast Decoupled Flow'])
    .describe('The recommended power flow algorithm.'),
  reasoning: z.string().describe('A brief explanation of why the recommended algorithm is suitable for the given grid configuration.'),
});
export type AlgorithmRecommendationOutput = z.infer<typeof AlgorithmRecommendationOutputSchema>;

export async function recommendAlgorithm(input: AlgorithmRecommendationInput): Promise<AlgorithmRecommendationOutput> {
  return algorithmRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'algorithmRecommendationPrompt',
  input: {schema: AlgorithmRecommendationInputSchema},
  output: {schema: AlgorithmRecommendationOutputSchema},
  prompt: `You are an expert in power flow algorithms. Given the following power grid configuration, recommend the most efficient algorithm (Newton-Raphson, Gauss-Seidel, DC Power Flow, or Fast Decoupled Flow) and explain your reasoning.\n\nGrid Configuration:\n- Number of Buses: {{{busCount}}}\n- Line Impedance Pattern: {{{lineImpedancePattern}}}\n- Number of Nodes: {{{nodeCount}}}\n\nRecommendation:`,
});

const algorithmRecommendationFlow = ai.defineFlow(
  {
    name: 'algorithmRecommendationFlow',
    inputSchema: AlgorithmRecommendationInputSchema,
    outputSchema: AlgorithmRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
